### ISSUE TITLE
Dictionaries doesn't work at all

### ISSUE THREAD

**Issue by mathialo** [mathialo/bython#1]
Since dictionaries uses curly braces they will cause a lot of errors when translating from bython to python. Dictionaries in python-files you import works.

**Comment by mathialo** [comment]
One can use the constructor for the [dict class](https://docs.python.org/3/library/stdtypes.html#dict)

**Comment by ole-tange** [comment]
Not good enough.

We really need to be able to write normal python code.

**Comment by ole-tange** [comment]
Maybe what is needed to parse the python code?

Here is a Python parser written in Python:

https://hg.python.org/cpython/file/80ab0b13eb04/Lib/lib2to3

That might be a helpful starting point.

**Comment by ole-tange** [comment]
Or this: https://github.com/davidhalter/parso
