### ISSUE TITLE
error when trying to install

### ISSUE THREAD

**Issue by ghost** [mathialo/bython#12]
im getting this in terminal when i try to install following instructions in the readme:
Makefile:5: recipe for target 'install' failed
make: *** [install] Error 1

is this a problem on my end or something with the makefile?

**Comment by mathialo** [comment]
This seems weird, which OS are you running?

It looks like the issue happens when the script is creating the install directory.

**Comment by return5** [comment]
ive tried it on both linux mint 18 and ubuntu 16.04, i get the same problem.

**Comment by mathialo** [comment]
Are you sure you are running the make script as root? The line that fails is when the script tries to make the install directory in `/usr/local`, and normal users are not allowed to do that.

**Comment by mathialo** [comment]
This is now an outdated issue, as the make script has been replaced with a proper python install script
