### ISSUE TITLE
alias "bython -c" to "by2py"

### ISSUE THREAD

**Issue by alkorang** [mathialo/bython#13]
There is `py2by`, but no `by2py`.
I think it would be better `bython -c` is aliased to `by2py` by default. :)

**Comment by mathialo** [comment]
I think the easiest solution to this is to add
``` bash
alias by2py='bython -c'
```
to `.bashrc`. I'm open to suggestions on how to make this the case by default, but I am unsure  how to do this in an elegant way without a lot of clutter.

**Comment by mathialo** [comment]
I have now added a hacky workaround for this. See the `ccce6969efe5bc2affc8656aa06d54e5d0728ee8` commit. It's currently only in the dev-branch, but will probably be merged into master at some point.
