### ISSUE TITLE
Dictionaries no longer work.

### ISSUE THREAD

**Issue by tr0yspradling** [mathialo/bython#23]
The compiler seems to have issues working with Python dictionaries. It converts the left curly brace to a colon.

**Comment by mathialo** [comment]
This is a known issue with the current implementation of the compiler. At the moment, you have to use the dictionary constructor directly.

For a discussion on the topic, consult the [introduction](https://github.com/mathialo/bython/blob/master/INTRODUCTION.md#21---dictionaries)
