### ISSUE TITLE
Transpiling?

### ISSUE THREAD

**Issue by numberisnan** [mathialo/bython#29]
Hi! I'm new to this project but i'm not sure if bython already supports transpiling to python, instead of just interpreting bython code. This isn't explicitly stated in the readme (to my understanding), so can bython transpile .by to .py?

**Comment by mathialo** [comment]
[Yes, it can](https://github.com/mathialo/bython/blob/master/INTRODUCTION.md#12---keeping-generated-python-files) :slightly_smiling_face:
