### ISSUE TITLE
Why ?

### ISSUE THREAD

**Issue by Somcr1510** [mathialo/bython#52]
One of the reasons why I love python is because I don't have to check brackets every time and spaces make code more readable.

**Comment by ribs351** [comment]
Because

**Comment by bitifet** [comment]
So, what's your problem?
Don't use it and you're done.

There are also lots of people who hate it just because of the same reason.

Which is the point of opening an issue just because you don't like it?

**Comment by Somcr1510** [comment]
That's the point don't use python at all.....😂😂😂😂

**Comment by bitifet** [comment]
> That's the point don't use python at all.....😂😂😂😂

I see...

Your only contribution in GitHub for more than a year is this shitty post.

I'm glad to know not using python worked for you. Now make you and us a favor and neither use GitHub issues.

Now, @mathialo can you be so kind of closing this (non) issue?

**Comment by Somcr1510** [comment]
I use python where I work....
Not everyone is just contributing to GitHub repos....
And yes real python programmers use indentation ....
 End of discussion......

**Comment by endasil** [comment]
> One of the reasons why I love python is because I don't have to check brackets every time and spaces make code more readable.

Developers of other programming languages use spaces too In order to make code more readable. The difference is that when developing in programming languages like C# that has brackets, the IDE automatically formats the code for you. You do not have to spend hours troubleshooting code because the spaces got wrong somewhere. In addition you save a huge amount of time by having the compiler catching many of the errors you need to run your code to discover in python.

**Comment by Rudxain** [comment]
NGL, I'm having a hard time recognizing which comments are:
- serious
- innocent jokes
- sarcasm/irony
- outright trolling

lol

**Comment by Somcr1510** [comment]
> NGL, I'm having a hard time recognizing which comments are:
> - serious
> - innocent jokes
> - sarcasm/irony
> - outright trolling

Exactly 💯, I started it as a joke and it quickly got serious. I don't hate anyone's preference but I just found out using curly braces in python is funny....😅😅😅 
But people get upset really quickly here.....😅😅😅

**Comment by Somcr1510** [comment]
> > NGL, I'm having a hard time recognizing which comments are:
> > - serious
> > - innocent jokes
> > - sarcasm/irony
> > - outright trolling
> 
> Exactly 💯, I started it as a joke and it quickly got serious. I don't hate anyone's preference but I just found out using curly braces in python is funny....😅😅😅 
> But people get upset really quick.....😅😅😅

**Comment by bitifet** [comment]
No one is upset for doing a joke.

But... opening an issue?

Do you open issues to every repositories you don't like or are not willing to use?

Well, too much time wasted here.

"I did a joke" is the perfect excuse when one have no arguments neither the integrity to rectify.

Cheers!

**Comment by Somcr1510** [comment]
@bitifet , You are such cry baby 🐥🍼😂🤣
