### ISSUE TITLE
IDE integration

### ISSUE THREAD

**Issue by intercepted16** [mathialo/bython#53]
Please add integration with IDE's such as JetBrains. And code editors such as VS Code.
Please, please. Then I could actually use it. I love it.

**Comment by ShakalnyKot** [comment]
> Then I could actually use it.

why does you need that so hard?

**Comment by intercepted16** [comment]
@ShakalnyKot So that I don't have 500 errors showing up in my IDE.

**Comment by ShakalnyKot** [comment]
> @ShakalnyKot So that I don't have 500 errors showing up in my IDE.

the errors will popup anyway in compile time or runtime, so you will not avoid it

**Comment by intercepted16** [comment]
what do you mean? I can convert it with `by2py`
but ideally I should be able to write `.by` code with IDE support

**Comment by lolouthefox** [comment]
> > @ShakalnyKot So that I don't have 500 errors showing up in my IDE.
> 
> the errors will popup anyway in compile time or runtime, so you will not avoid it

I think he's talking about the fact that the IDE thinks that the brackets are not supposed to be here and shows a squiggly red line.
![image](https://github.com/user-attachments/assets/ac4a19a9-684b-4722-8d03-b4fc2800f6ff)
I agree with @intercepted16, there probably should be IDE integration using a plugin, mostly for PyCharm and VSCode as they are the most used softwares.

**Comment by lolouthefox** [comment]
But it's a duplicate of #32 actually

**Comment by intercepted16** [comment]
Yeah, just realised it's a duplicate. Closing the issue now.
