### ISSUE TITLE
Converter from indented code to braced

### ISSUE THREAD

**Issue by ole-tange** [mathialo/bython#6]
When working with files written by others it would be nice if you could convert their code to braced code.

By being able to convert both ways you open up for making an emacs-filter that inserts braces when opening a file and removes them when saving the file. Give that emacs can run .gz-files through a filter it ought to be easy to do that for .py-files, too.

PS: And thank you. I have been holding off using Python for anything serious because of the missing braces. Now that hurdle is gone.

**Comment by mathialo** [comment]
This is now a feature, a converter called py2by is added. To make use of this you will have to fully uninstall the program and reinstall it. Thanks for the suggestion.
